export const USER_LOGIN_REQ = 'USER_LOGIN_REQ'
export const USER_LOGIN_SUC = 'USER_LOGIN_SUC'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_REG_REQ = 'USER_REG_REQ'
export const USER_REG_SUC = 'USER_REG_SUC'
export const USER_REG_FAIL = 'USER_REG_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'
